#!/bin/sh
#                  _                _    _               
#  _ __  ___  ___ | |_  __ _  _ __ | |_ (_) _ __    __ _ 
# | '__|/ _ \/ __|| __|/ _` || '__|| __|| || '_ \  / _` |
# | |  |  __/\__ \| |_| (_| || |   | |_ | || | | || (_| |
# |_|   \___||___/ \__|\__,_||_|    \__||_||_| |_| \__, |
#                                                  |___/ 
#
# __ DESCRIPTION __
# preocesses the reboot, shutdown and refresh i3 commands


CHOICE=$(echo -e "i3-Reload Config\ni3-Restart\ni3-Exit\nReboot\nShutdown" | \
	     dmenu -i -p "What do: ")

if [[ $CHOICE == "i3-Restart" ]]; then
    i3-msg restart && xcowsay "Doing \"$CHOICE\""
elif [[ $CHOICE == "i3-Reload Config" ]]; then
    i3-msg reload  && xcowsay "Doing \"$CHOICE\""
elif [[ $CHOICE == "i3-Exit" ]]; then
    i3-msg exit && xcowsay "Doing \"$CHOICE\""
elif [[ $CHOICE == "Reboot" ]]; then
    sudo -A reboot && xcowsay "Doing \"$CHOICE\""
elif [[[ $CHOICE == "Shutdown" ]]; then
    sudo -A shutdown -h now && xcowsay "Doing \"$CHOICE\""
fi
